Rework db and logic of project
itsnotganeva/intexsoft-test-task pull request #2
Opened 2022-02-16 13:53 UTC by itsnotganeva

2022-02-17 06:47 UTC, romaasanovich requested changes

2022-02-17 06:47 UTC, romaasanovich commented on src/main/java/by/ganevich/config/DatabaseConfig.java
> +        properties.put(Environment.SHOW_SQL, "true");
Вынести `SHOW_SQL` в `appplication.properies`.

2022-02-17 06:47 UTC, romaasanovich commented on src/main/java/by/ganevich/entity/Bank.java
> +            fetch = FetchType.EAGER)
Почитай про  `FetchType` и как лучше его использовать.

2022-02-17 06:47 UTC, romaasanovich commented on src/main/java/by/ganevich/entity/BankAccount.java
> +    private Client accountOwner;
`accountOwner` -> `owner`.

2022-02-17 06:47 UTC, romaasanovich commented on src/main/java/by/ganevich/entity/BankAccount.java
Может лучше использовать один список `Set<Transaction>` и разделять их уже по типу Транзакции?

2022-02-17 06:47 UTC, romaasanovich commented on src/main/java/by/ganevich/entity/Client.java
> +    private Set<Transaction> sentTransactions;
Почему только sentTransactions?

2022-02-17 06:47 UTC, romaasanovich commented on src/main/java/by/ganevich/exception/EntityNotFoundException.java
>      private static final long serialVersionUID = 1L;
За что отвечает это поле?

2022-02-17 06:47 UTC, romaasanovich commented on src/main/java/by/ganevich/io/Interactive.java
Привести к единому виду:
В этомклассе `@Autowired`, а в некоторых мествх юзаем через `@AllArgsConstructor`

2022-02-17 06:47 UTC, romaasanovich commented on src/main/java/by/ganevich/service/TransactionService.java
> +
Схожая логика, можно вынести из под if - else блока

2022-02-17 06:47 UTC, romaasanovich commented on src/main/java/by/ganevich/service/TransactionService.java
> +        if (sumOfMoney <= senderSum) {
А если сумма не попадет в этот `if`, все равон создаст транзакцию?

2022-02-22 14:19 UTC, romaasanovich requested changes

2022-02-22 14:19 UTC, romaasanovich commented on src/main/java/by/ganevich/entity/Bank.java
> +    @Fetch(FetchMode.JOIN)
Почитай что делает @Fetch(FetchMode.JOIN), и нужна ли она тебе?
Возможно хватит @OneToMany 
И почитай про cascade = CascadeType и какой использовать.

2022-02-22 17:04 UTC, itsnotganeva commented on src/main/java/by/ganevich/entity/Bank.java
> +    @Fetch(FetchMode.JOIN)
Удалил @fetch и добавил EntityGraph

2022-02-22 17:05 UTC, itsnotganeva commented on src/main/java/by/ganevich/service/TransactionService.java
> +        if (sumOfMoney <= senderSum) {
Исправил

2022-02-22 17:05 UTC, itsnotganeva commented on src/main/java/by/ganevich/service/TransactionService.java
> +
Исправил

2022-02-22 17:05 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/Interactive.java
Исправил

2022-02-22 17:05 UTC, itsnotganeva commented on src/main/java/by/ganevich/exception/EntityNotFoundException.java
>      private static final long serialVersionUID = 1L;
Исправил

2022-02-22 17:05 UTC, itsnotganeva commented on src/main/java/by/ganevich/entity/Client.java
> +    private Set<Transaction> sentTransactions;
Исправил

2022-02-22 17:06 UTC, itsnotganeva commented on src/main/java/by/ganevich/entity/BankAccount.java
> +    private Client accountOwner;
Исправил

2022-02-23 07:08 UTC, romaasanovich approved these changes

2022-02-23 07:08 UTC, merged