rework interactive of app
itsnotganeva/intexsoft-test-task pull request #5
Opened 2022-03-02 14:57 UTC by itsnotganeva

2022-03-04 07:14 UTC, romaasanovich requested changes

2022-03-04 07:14 UTC, romaasanovich commented on src/main/java/by/ganevich/io/CommandDescriptor.java
> +    private HashMap<Integer, String> parameters;
Давай сделаем так, чтобы мы команду писали одним словом и параметры передапвали с названием параметра, а не черз пробел параметры. 
Например createClient firstName=*** lastName=****  и т. п.
Соответственно изменим логику парсинга и использование этого параметра.

2022-03-04 07:14 UTC, romaasanovich commented on src/main/java/by/ganevich/io/factory/CommandFactory.java
> +    private List<ICommand> commands;
Давай используем Map<String, IComand>, где ключ это название команды.
Так будет удобнее.

2022-03-04 07:14 UTC, romaasanovich commented on src/main/java/by/ganevich/io/factory/CommandFactory.java
> +        collectCommands();
При вызове мы будем постоянно добавлять в коллекцию команды?
Давай сделаем это на старте приложения один раз.

2022-03-04 07:14 UTC, romaasanovich commented on src/main/java/by/ganevich/io/CommandExecutor.java
> +        Object commandResult = commandFactory.getCommand(commandDescriptor).execute(commandDescriptor);
Если в фактори не нашли команды?)

2022-03-04 07:14 UTC, romaasanovich commented on src/main/java/by/ganevich/io/commands/ICommand.java
> +package by.ganevich.io.commands;
Давай добавим, чтобы для каждой команды при написании $название_команды$ help выводило подсказку, что надо вводить и какие параметры есть.

2022-03-04 07:14 UTC, romaasanovich commented on src/main/java/by/ganevich/io/commands/HelpCommand.java
> +        String helpCommand = "create bank bank_name individual_commission industrial_commission \n"
Давай в этой команде выведем просто список команд с их описанием.
А у каждой команды уже выведем детальное ее описание.

2022-03-04 07:14 UTC, romaasanovich commented on src/main/java/by/ganevich/io/factory/CommandFactory.java
> +        commands.add(helpCommand);
Добавь exit команду, чтобы она выходила из приложения.

2022-03-04 17:15 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/CommandDescriptor.java
> +    private HashMap<Integer, String> parameters;
Исправил

2022-03-04 17:15 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/factory/CommandFactory.java
> +    private List<ICommand> commands;
Исправил

2022-03-04 17:15 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/factory/CommandFactory.java
> +        collectCommands();
Исправил

2022-03-04 17:15 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/CommandExecutor.java
> +        Object commandResult = commandFactory.getCommand(commandDescriptor).execute(commandDescriptor);
Исправил

2022-03-04 17:15 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/commands/ICommand.java
> +package by.ganevich.io.commands;
Исправил

2022-03-04 17:16 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/commands/HelpCommand.java
> +        String helpCommand = "create bank bank_name individual_commission industrial_commission \n"
Исправил

2022-03-04 17:16 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/factory/CommandFactory.java
> +        commands.add(helpCommand);
Исправил

2022-03-09 11:22 UTC, romaasanovich commented on src/main/java/by/ganevich/io/ConsoleLineParser.java
> +      //  createClient name=Matvey type=individual
Ненужный коментарий. Удали его плиз.

2022-03-09 11:26 UTC, romaasanovich commented on src/main/java/by/ganevich/io/commands/AddClientToBankCommand.java
> +
зачем пустая строка?

2022-03-09 11:27 UTC, romaasanovich commented on src/main/java/by/ganevich/io/commands/AddClientToBankCommand.java
> +            return null;
Везде схожая логика получения help описания

2022-03-09 11:28 UTC, romaasanovich commented on src/main/java/by/ganevich/io/commands/ReadTransactionsCommand.java
> +
пустая строка

2022-03-09 11:43 UTC, romaasanovich commented on src/main/java/by/ganevich/io/factory/CommandFactory.java
> +    public Map<String, ICommand> collectCommands() {
Давай вызывать один раз и используя метод @PostConstuct.

2022-03-09 11:44 UTC, romaasanovich commented on src/main/java/by/ganevich/io/factory/CommandFactory.java
> +    public ICommand getCommand(CommandDescriptor commandDescriptor, Map<String, ICommand> commands) {
Избавиться от Map<String, ICommand> commands

2022-03-09 14:05 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/ConsoleLineParser.java
> +      //  createClient name=Matvey type=individual
Исправил

2022-03-09 14:05 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/commands/AddClientToBankCommand.java
> +
Исправил

2022-03-09 14:05 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/commands/AddClientToBankCommand.java
> +            return null;
Исправил

2022-03-09 14:05 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/commands/ReadTransactionsCommand.java
> +
Исправил

2022-03-09 14:06 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/factory/CommandFactory.java
> +    public Map<String, ICommand> collectCommands() {
Исправил

2022-03-09 14:06 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/factory/CommandFactory.java
> +    public ICommand getCommand(CommandDescriptor commandDescriptor, Map<String, ICommand> commands) {
Исправил

2022-03-09 16:09 UTC, romaasanovich commented on src/main/java/by/ganevich/io/commands/BaseCommand.java
> +        return null;
Почему не сделать этот метод абстрактным?

2022-03-09 16:11 UTC, romaasanovich commented on src/main/java/by/ganevich/io/CommandResult.java
> +    private T t;
Что такое Т?

2022-03-09 16:12 UTC, romaasanovich commented on src/main/java/by/ganevich/io/commands/AddClientToBankCommand.java
> +    private final CommandResult commandResult;
Зачем создавать private final CommandResult commandResult?
Можно просто возвращать из метода результат

2022-03-09 16:14 UTC, romaasanovich commented on src/main/java/by/ganevich/io/commands/AddClientToBankCommand.java
> +    public CommandResult getDescription() {
Давай возвращать строку из getDescription().

2022-03-09 16:18 UTC, romaasanovich commented on src/main/java/by/ganevich/io/commands/BaseCommand.java
> +    public CommandResult getDescription() {
Давай в абстрактном классе реализуем возврат CommandResult в getDescription и в реализациях уже возвращать строковое знаечение в абстрактном методе getDescriptionValue();. 
Т. е. метод будет выглядеть так:
 public CommandResult getDescription() {
        CommandResult comandResult = new ComandResult();
        comandResult.setT(getDescription());
        return comandResult;
    }
    
public abstract String getDescriptionValue();

2022-03-09 16:20 UTC, romaasanovich commented on src/main/java/by/ganevich/io/commands/DeleteBankCommand.java
> +        commandResult.setT(null);
Возвращай в таких случаях какое-нибудь сообщение об успешной операции.

2022-03-10 08:01 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/commands/BaseCommand.java
> +        return null;
Исправил

2022-03-10 08:01 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/CommandResult.java
> +    private T t;
Исправил

2022-03-10 08:01 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/commands/AddClientToBankCommand.java
> +    private final CommandResult commandResult;
Исправил

2022-03-10 08:01 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/commands/AddClientToBankCommand.java
> +    public CommandResult getDescription() {
Исправил

2022-03-10 08:01 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/commands/BaseCommand.java
> +    public CommandResult getDescription() {
Исправил

2022-03-10 08:01 UTC, itsnotganeva commented on src/main/java/by/ganevich/io/commands/DeleteBankCommand.java
> +        commandResult.setT(null);
Исправил

2022-03-10 09:06 UTC, romaasanovich approved these changes

2022-03-10 09:07 UTC, merged