add controllers
itsnotganeva/intexsoft-test-task pull request #6
Opened 2022-03-11 12:20 UTC by itsnotganeva

2022-03-12 09:38 UTC, romaasanovich commented on src/main/java/by/ganevich/controller/BankAccountController.java
> +    @PostMapping(value = "/bankAccounts")
Не совсем корректное именование:
https://betterprogramming.pub/10-best-practices-for-naming-rest-api-endpoints-442ae592a3a0

2022-03-12 09:39 UTC, romaasanovich commented on src/main/java/by/ganevich/controller/BankController.java
> +    public ResponseEntity<?> update(@PathVariable(name = "id") Long id, @RequestBody Bank bank) {
Нельзя использовать entity в контроллерах, почитай про DTO-объекты и добавь их.

2022-03-12 09:40 UTC, romaasanovich commented on src/main/java/by/ganevich/controller/ClientController.java
> +        return clients != null &&  !clients.isEmpty()
Можешь просто возвразать пустой массив

2022-03-12 09:42 UTC, romaasanovich commented on src/main/java/by/ganevich/controller/ClientController.java
> +        return client != null
Здесь лучше вернуть ошибку с корректным сообщением, а не 404

2022-03-12 09:43 UTC, romaasanovich commented on src/main/java/by/ganevich/controller/TransactionController.java
> +    public ResponseEntity<?> create(@PathVariable(name = "senderAccountNumber") Integer senderAccountNumber,
Почему метож create?

2022-03-12 09:44 UTC, romaasanovich requested changes
need to rework

2022-03-13 18:55 UTC, itsnotganeva commented on src/main/java/by/ganevich/controller/BankAccountController.java
> +    @PostMapping(value = "/bankAccounts")
Исправил

2022-03-13 18:55 UTC, itsnotganeva commented on src/main/java/by/ganevich/controller/BankController.java
> +    public ResponseEntity<?> update(@PathVariable(name = "id") Long id, @RequestBody Bank bank) {
Исправил

2022-03-13 18:55 UTC, itsnotganeva commented on src/main/java/by/ganevich/controller/TransactionController.java
> +    public ResponseEntity<?> create(@PathVariable(name = "senderAccountNumber") Integer senderAccountNumber,
Исправил

2022-03-14 09:38 UTC, romaasanovich commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-ui -->
ненужный коммент

2022-03-15 09:58 UTC, romaasanovich commented on src/main/java/by/ganevich/controller/BankAccountController.java
> +        return new ResponseEntity<>(HttpStatus.CREATED);
Возвращай HttpStatus.OK, так чаще всего описывают успешный вызов контроллера.

2022-03-15 09:58 UTC, romaasanovich commented on src/main/java/by/ganevich/controller/BankAccountController.java
> +                : new ResponseEntity<>(HttpStatus.NOT_FOUND);
Опять используешь HttpStatus.NOT_FOUND, возвращай пустой лист.

2022-03-15 09:59 UTC, romaasanovich commented on src/main/java/by/ganevich/controller/BankAccountController.java
> +        return bankAccounts != null && !bankAccounts.isEmpty()
Во многих местах такая проверка
Вынеси в отдельный метод или используй CollectionUtils

2022-03-15 09:59 UTC, romaasanovich commented on src/main/java/by/ganevich/controller/BankController.java
> +
пустая стока

2022-03-15 10:03 UTC, romaasanovich commented on src/main/java/by/ganevich/controller/TransactionController.java
> +            @PathVariable(name = "id") @Parameter(description = "id of client") Long id,
Используй RequestParameters, когда это просто параметры запроса, в этом случае это {dateBefore}/{dateAfter}, а {id} оставь PathVariable.

2022-03-15 10:04 UTC, romaasanovich commented on src/main/java/by/ganevich/controller/TransactionController.java
> +    public ResponseEntity<?> makeTransaction(
Здесь возможно стоит завести DTO, чтобы не плодить кол-во параметров. и так будет более читаемо и удобно поддерживать.

2022-03-15 10:05 UTC, romaasanovich commented on src/main/java/by/ganevich/dto/BankAccountDto.java
> +    @JsonProperty(value = "id")
Проверь стоит ли добавлять  @JsonProperty(value = "id"), может просто оставить без этой аннотации и укзать другую аннотацию над классом?

2022-03-15 11:10 UTC, itsnotganeva commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-ui -->
Исправил

2022-03-15 11:10 UTC, itsnotganeva commented on src/main/java/by/ganevich/controller/BankAccountController.java
> +        return new ResponseEntity<>(HttpStatus.CREATED);
Исправил

2022-03-15 11:11 UTC, itsnotganeva commented on src/main/java/by/ganevich/controller/BankAccountController.java
> +                : new ResponseEntity<>(HttpStatus.NOT_FOUND);
Исправил

2022-03-15 11:12 UTC, itsnotganeva commented on src/main/java/by/ganevich/controller/BankController.java
> +
Исправил

2022-03-15 11:30 UTC, itsnotganeva commented on src/main/java/by/ganevich/controller/TransactionController.java
> +            @PathVariable(name = "id") @Parameter(description = "id of client") Long id,
Исправил

2022-03-15 12:21 UTC, itsnotganeva commented on src/main/java/by/ganevich/controller/TransactionController.java
> +    public ResponseEntity<?> makeTransaction(
Исправил

2022-03-15 12:27 UTC, itsnotganeva commented on src/main/java/by/ganevich/dto/BankAccountDto.java
> +    @JsonProperty(value = "id")
Исправил

2022-03-16 14:56 UTC, romaasanovich approved these changes

2022-03-16 14:56 UTC, merged